export default {
  ADD_TODO: 'ADD_TODO',
  GET_TODO: 'GET_TODO',
  GET_TODO_RECEIVE: 'GET_TODO_RECEIVE',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  LOADING_TODO: 'LOADING_TODO',
  RESET_TODO: 'RESET_TODO',
};
